// Cyber Outbreak \u2014 card deck integrated from uploads/cards.xlsx + world data with real coordinates.

export const CATEGORIES = {
  initial:     { id: 'initial',     label: 'Initial Compromise', color: '#e28b90', icon: '\u25c8' },
  pivot:       { id: 'pivot',       label: 'Pivot & Escalate',   color: '#cbaa6a', icon: '\u2b17' },
  c2:          { id: 'c2',          label: 'C2 & Exfil',         color: '#c8925a', icon: '\u21c5' },
  persistence: { id: 'persistence', label: 'Persistence',        color: '#b78cff', icon: '\u221e' },
  procedure:   { id: 'procedure',   label: 'Procedure',          color: '#9184d9', icon: '\u25a3' },
  inject:      { id: 'inject',      label: 'Inject',             color: '#9aa5b5', icon: '\u26a1' },
};

export const PROCEDURES = [
  { id: 'p_siem', type: 'procedure', title: 'SIEM Log Analysis',
    description: 'Query the central log platform for the weird stuff hiding in the noise \u2014 assuming anyone remembered to point every source at it.',
    tools: ['SOF-ELK', 'JPCert Tools Analysis'] },
  { id: 'p_server', type: 'procedure', title: 'Server Analysis',
    description: 'Pull apart a suspect server: services, logs, users, recent changes \u2014 and the changelog nobody filled out.',
    tools: ['DeepBlueCLI', 'SANS Analysis Cheat Sheets'] },
  { id: 'p_firewall', type: 'procedure', title: 'Firewall Log Review',
    description: 'Read the perimeter\u2019s diary: odd destinations, denied-then-allowed patterns, and that one rule someone added \u201ctemporarily\u201d in 2019.',
    tools: ['SOF-ELK'] },
  { id: 'p_netflow', type: 'procedure', title: 'Network Analysis',
    description: 'Study traffic metadata for beacons, tunnels and long, chatty connections \u2014 the network never lies, it just talks in a language nobody bothered to learn.',
    tools: ['RITA', 'Security Onion', 'AI-Hunter'] },
  { id: 'p_seg', type: 'procedure', title: 'Internal Segmentation',
    description: 'Wall off network segments and watch what tries to cross \u2014 discover, four years late, that everything is on the flat network anyway.',
    tools: ['netsh advfirewall', 'Windows Defender Firewall', 'iptables'] },
  { id: 'p_espa', type: 'procedure', title: 'Endpoint Security Protection Analysis',
    description: 'Interrogate the AV/EDR console for the detections everyone ignored, filed under \u201cinvestigate later,\u201d roughly forever ago.',
    tools: ['Check with your vendor \u2014 they miss you and always want to chat.'] },
  { id: 'p_ueba', type: 'procedure', title: 'User & Entity Behavior Analytics',
    description: 'Baseline everyone, then hunt whoever stopped acting like themselves \u2014 turns out that\u2019s also what it looks like when someone finally goes on vacation.',
    tools: ['LogonTracer'] },
  { id: 'p_endpoint', type: 'procedure', title: 'Endpoint Analysis',
    description: 'Deep-dive a workstation: processes, autoruns, event logs, artifacts, and forty browser toolbars nobody can explain.',
    tools: ['DeepBlueCLI', 'SANS IR Cheat Sheets'] },
  { id: 'p_iso', type: 'procedure', title: 'Isolation',
    description: 'Cut a suspect host off the network and see what screams \u2014 usually the finance intern, never the attacker. A response move; it finds nothing by itself.',
    tools: ['Switch and Router Commands'] },
  { id: 'p_crisis', type: 'procedure', title: 'Crisis Management',
    description: 'Brief the execs, prep notifications, keep the org from panicking with a slide titled \u201cWe Have This Under Control.\u201d Vital \u2014 but it detects nothing.',
    tools: ['A good notification strategy'] },
];

export const ATTACKS = [
  // \u2014 Initial Compromise \u2014
  { id: 'ic_phish', type: 'initial', title: 'Phish',
    description: 'A convincing email, a poisoned link, a harvested credential. The oldest trick still works.',
    detection: ['p_firewall', 'p_espa'],
    tools: ['evilginx', 'GoPhish', 'CredSniper'],
    siteTypes: ['hq', 'office'],
    brief: 'Users at {node} are reporting suspicious emails from "IT Support".' },
  { id: 'ic_web', type: 'initial', title: 'Web Server Compromise',
    description: 'A shaky web app and a little SQL injection hand over the front door.',
    detection: ['p_server', 'p_siem', 'p_netflow'],
    tools: ['Zed Attack Proxy', 'sqlmap', 'Burp Proxy'],
    siteTypes: ['datacenter', 'cloud'],
    brief: 'The web team noticed strange requests hammering a server at {node}.' },
  { id: 'ic_cloud', type: 'initial', title: 'External Cloud Access',
    description: 'Your cloud tenant, someone else\u2019s login. Legitimate portal, illegitimate visitor.',
    detection: ['p_siem'],
    tools: ['SprayingToolkit', 'CredKing', 'FireProx'],
    siteTypes: ['cloud'],
    brief: 'Sign-in alerts from unfamiliar locations are hitting accounts at {node}.' },
  { id: 'ic_insider', type: 'initial', title: 'Insider Threat',
    description: 'The attacker has a badge, a desk, and a grudge.',
    detection: ['p_ueba'],
    tools: ['Long hours', 'Being considered an FTE', 'Working with HR (eventually)'],
    siteTypes: ['hq', 'office', 'soc', 'factory'],
    brief: 'HR quietly flagged unusual after-hours access at {node}.' },
  { id: 'ic_spray', type: 'initial', title: 'Password Spray',
    description: 'One common password tried against every account. Statistically, someone chose "Company123".',
    detection: ['p_siem', 'p_ueba', 'p_firewall'],
    tools: ['SprayingToolkit', 'FireProx', 'Hydra', 'DomainPasswordSpray'],
    siteTypes: ['hq', 'office', 'cloud'],
    brief: 'Failed logins spiked overnight across accounts at {node}.' },
  { id: 'ic_trust', type: 'initial', title: 'Trusted Relationship',
    description: 'A partner\u2019s network was the soft way into yours.',
    detection: ['p_siem', 'p_ueba'],
    tools: ['An unfounded trust in business partners who are complete strangers'],
    siteTypes: ['factory', 'office', 'datacenter'],
    brief: 'A partner connection into {node} is behaving oddly.' },
  { id: 'ic_social', type: 'initial', title: 'Social Engineering',
    description: 'A phone call, a story, and a helpful employee. No malware required.',
    detection: ['p_espa'],
    tools: ['Phone', 'A goal and a dream of evil', 'People trusting people'],
    siteTypes: ['hq', 'office'],
    brief: 'The help desk at {node} reset a password for a very convincing caller.' },
  { id: 'ic_byod', type: 'initial', title: 'Bring Your Own (Exploited) Device',
    description: 'That personal laptop on the office Wi-Fi came pre-compromised.',
    detection: ['p_firewall', 'p_netflow'],
    tools: ['The belief that BYOD is a worthy cost savings'],
    siteTypes: ['hq', 'office'],
    brief: 'A personal device at {node} tripped a network alert, then went quiet.' },
  { id: 'ic_extsvc', type: 'initial', title: 'Exploitable External Service',
    description: 'An unpatched internet-facing service met Metasploit. Metasploit won.',
    detection: ['p_firewall', 'p_server'],
    tools: ['Metasploit', 'Failed patching process', 'Unauthorized system stood up by an employee'],
    siteTypes: ['datacenter', 'cloud'],
    brief: 'An internet-facing service at {node} restarted at 3 a.m. Nobody scheduled that.' },
  { id: 'ic_stuff', type: 'initial', title: 'Credential Stuffing',
    description: 'Passwords reused from someone else\u2019s breach unlock your services too.',
    detection: ['p_server', 'p_ueba'],
    tools: ['Burp', 'Hydra', 'Users registering for services with work email addresses'],
    siteTypes: ['cloud', 'office'],
    brief: 'A wave of logins with valid passwords but all the wrong browsers hit {node}.' },

  // \u2014 Pivot & Escalate \u2014
  { id: 'pe_spray', type: 'pivot', title: 'Internal Password Spray',
    description: 'The spray moves inside \u2014 one password against every internal account.',
    detection: ['p_ueba', 'p_siem'],
    tools: ['DomainPasswordSpray'],
    siteTypes: ['hq', 'office', 'datacenter', 'cloud', 'soc', 'factory'] },
  { id: 'pe_kerb', type: 'pivot', title: 'Kerberoasting',
    description: 'Service tickets harvested and cracked offline into service-account passwords.',
    detection: ['p_siem', 'p_ueba', 'p_seg'],
    tools: ['GetUserSPNs.py (Impacket)', 'Hashcat'],
    siteTypes: ['hq', 'datacenter'] },
  { id: 'pe_ad', type: 'pivot', title: 'Weaponizing Active Directory',
    description: 'BloodHound maps every path to Domain Admin. There are several.',
    detection: ['p_siem', 'p_ueba', 'p_seg'],
    tools: ['BloodHound', 'DeathStar', 'CrackMapExec'],
    siteTypes: ['hq', 'datacenter'] },
  { id: 'pe_stuff', type: 'pivot', title: 'Credential Stuffing',
    description: 'Credentials scraped from shares and files open doors all across the network.',
    detection: ['p_siem', 'p_ueba', 'p_seg'],
    tools: ['ADExplorer.exe', 'Invoke-ShareFinder', 'Find-InterestingFile', 'MailSniper'],
    siteTypes: ['hq', 'office'] },
  { id: 'pe_svc', type: 'pivot', title: 'New Service Creation',
    description: 'A freshly created service running as SYSTEM escalates the foothold.',
    detection: ['p_endpoint', 'p_espa'],
    tools: ['Metasploit getsystem', 'Post-exploitation scripts'],
    siteTypes: ['hq', 'office', 'datacenter', 'factory'] },
  { id: 'pe_lpe', type: 'pivot', title: 'Local Privilege Escalation',
    description: 'A local exploit quietly turns "user" into "administrator".',
    detection: ['p_endpoint', 'p_espa'],
    tools: ["PowerSploit's PowerUp", 'Meterpreter post-exploitation scripts'],
    siteTypes: ['hq', 'office', 'factory'] },
  { id: 'pe_poison', type: 'pivot', title: 'Broadcast / Multicast Protocol Poisoning',
    description: 'Responder answers LLMNR, NBT-NS and mDNS lookups \u2014 and collects hashes all day.',
    detection: ['p_ueba', 'p_firewall'],
    tools: ['Responder', 'CredDefense Toolkit (defense)'],
    siteTypes: ['hq', 'office', 'factory'] },

  // \u2014 C2 & Exfil \u2014
  { id: 'ce_http', type: 'c2', title: 'HTTP as Exfil',
    description: 'Your data leaves in plain HTTP, blending into everyday web noise.',
    detection: ['p_netflow'],
    tools: ['Metasploit reverse HTTP payloads', 'VSAgent', 'Prismatica'],
    siteTypes: ['hq', 'office', 'datacenter'] },
  { id: 'ce_https', type: 'c2', title: 'HTTPS as Exfil',
    description: 'Encrypted beaconing to attacker infrastructure, disguised as normal browsing.',
    detection: ['p_netflow'],
    tools: ['Metasploit reverse HTTPS payloads', 'SILENTTRINITY'],
    siteTypes: ['hq', 'office', 'datacenter'] },
  { id: 'ce_dns', type: 'c2', title: 'DNS as C2',
    description: 'Commands and data smuggled out one weird DNS query at a time.',
    detection: ['p_netflow'],
    tools: ['dnscat2'],
    siteTypes: ['hq', 'office', 'datacenter', 'factory'] },
  { id: 'ce_bits', type: 'c2', title: 'Windows BITS',
    description: 'Windows\u2019 own Background Intelligent Transfer Service quietly ferries the payload.',
    detection: ['p_netflow'],
    tools: ['bitsadmin'],
    siteTypes: ['hq', 'office'] },
  { id: 'ce_saas', type: 'c2', title: 'Gmail / Tumblr / Salesforce / Twitter as C2',
    description: 'Commands hide inside traffic to services you would never dream of blocking.',
    detection: ['p_netflow'],
    tools: ['Gcat', 'Sneaky Creeper'],
    siteTypes: ['hq', 'office', 'cloud'] },
  { id: 'ce_front', type: 'c2', title: 'Domain Fronting as C2',
    description: 'C2 traffic wears a trusted CDN domain as a mask.',
    detection: ['p_netflow'],
    tools: ['Cobalt Strike'],
    siteTypes: ['hq', 'datacenter', 'cloud'] },

  // \u2014 Persistence \u2014
  { id: 'ps_malware', type: 'persistence', title: 'Malicious Service / Just Malware',
    description: 'A new service with an official-sounding name restarts the implant on every boot.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Metasploit persistence', 'autoruns.exe', 'msconfig.exe', 'SILENTTRINITY'],
    siteTypes: ['hq', 'office', 'datacenter'] },
  { id: 'ps_dll', type: 'persistence', title: 'DLL Attacks',
    description: 'A hijacked DLL loads the attacker\u2019s code inside a process you trust.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['PowerSploit', 'InvisiMole'],
    siteTypes: ['hq', 'office'] },
  { id: 'ps_driver', type: 'persistence', title: 'Malicious Driver',
    description: 'Kernel-level persistence \u2014 the rootkit sits below everything you trust.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Pasam', 'Wingbird', 'SeaDuke', 'ROCKBOOT', 'Alureon'],
    siteTypes: ['datacenter', 'factory'] },
  { id: 'ps_user', type: 'persistence', title: 'New User Added',
    description: 'Meet "svc_backup2", an administrator account nobody remembers creating.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Metasploit', 'Cobalt Strike'],
    siteTypes: ['hq', 'datacenter', 'cloud'] },
  { id: 'ps_shim', type: 'persistence', title: 'Application Shimming',
    description: 'A compatibility shim quietly patches the attacker back in on every launch.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Windows Assessment and Deployment Kit (ADK)'],
    siteTypes: ['hq', 'office'] },
  { id: 'ps_plugin', type: 'persistence', title: 'Malicious Browser Plugins',
    description: 'A helpful-looking extension that reads everything you type.',
    detection: ['p_espa', 'p_endpoint', 'p_firewall', 'p_netflow'],
    tools: ['"Grammarly is a keylogger"', 'graniet/chromebackdoor'],
    siteTypes: ['hq', 'office'] },
  { id: 'ps_logon', type: 'persistence', title: 'Logon Scripts',
    description: 'Every login reinstalls the implant. Rise and shine.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Meterpreter persistence'],
    siteTypes: ['hq', 'office', 'datacenter'] },
  { id: 'ps_firm', type: 'persistence', title: 'Evil Firmware',
    description: 'Below the OS, above suspicion. Reimaging will not save you.',
    detection: ['p_espa', 'p_endpoint'],
    tools: ['Hacking Team UEFI rootkit', 'BadBIOS (\u2026maybe)'],
    siteTypes: ['factory', 'datacenter'] },
  { id: 'ps_access', type: 'persistence', title: 'Accessibility Features',
    description: 'Sticky Keys now launches a shell. Five taps of Shift to own the box.',
    detection: ['p_endpoint', 'p_espa'],
    tools: ['Bash Bunny', 'USB Rubber Ducky'],
    siteTypes: ['hq', 'office'] },
];

export const INJECTS = [
  { id: 'in_honey', type: 'inject', title: 'Honeypots Deployed',
    description: 'Good news \u2014 the decoys were live, and something touched them. The Pivot & Escalate card is shown to the table.',
    effect: { kind: 'revealCategory', category: 'pivot' } },
  { id: 'in_pentest', type: 'inject', title: 'It Was a Pentest',
    description: 'Ha! You were never under attack. The CEO hired an external firm to run an unannounced red team. Bittersweet: no breach \u2014 but you were compromised.',
    effect: { kind: 'endsGame', result: 'pentest' } },
  { id: 'in_pastebin', type: 'inject', title: 'Data Uploaded to Pastebin',
    description: 'Internal sensitive data just appeared on Pastebin. Your customers are learning about the incident from the media. Bring in Legal and Upper Management.',
    effect: { kind: 'flavor', mapEvent: 'highlightRandom' } },
  { id: 'in_splunk', type: 'inject', title: 'SIEM Analyst Returns from Splunk Training',
    description: 'Fresh from training and dangerous with a query bar. Training is awesome \u2014 you should get some.',
    effect: { kind: 'modifier', value: 2, label: '+2 on your next roll' } },
  { id: 'in_takeproc', type: 'inject', title: 'Take One Procedure Card Away',
    description: 'Sometimes procedures fail. Sometimes nobody can find one when it matters most. Nobody\u2019s perfect. Sorry.',
    effect: { kind: 'loseProcedure' } },
  { id: 'in_giveproc', type: 'inject', title: 'Give the Defenders a Random Procedure Card',
    description: 'For whatever reason, everyone forgot they had this. It must be Monday. A procedure returns to the table.',
    effect: { kind: 'gainProcedure' } },
  { id: 'in_fmla', type: 'inject', title: 'Lead Handler Has a Baby, Takes FMLA Leave',
    description: 'The one person who pretty much runs the whole IR process is out. Quiet listeners in the back: now is your time. Shine!',
    effect: { kind: 'modifier', value: -2, label: '\u22122 on your next roll' } },
  { id: 'in_bobby', type: 'inject', title: 'Bobby the Intern Kills the System You Are Reviewing',
    description: 'This. Happens. Far. Too. Often. (No \u2014 murder is never okay. Don\u2019t even think it.)',
    effect: { kind: 'skipTurn' } },
  { id: 'in_legal', type: 'inject', title: 'Legal Takes Your Only Skilled Handler Into a Meeting',
    description: 'The legal team needs your best handler for "Very Important Reasons". They may never come back.',
    effect: { kind: 'modifier', value: -2, label: '\u22122 on your next roll' } },
  { id: 'in_newproc', type: 'inject', title: 'Management Approves a New Procedure',
    description: 'Knights in shining business suits! Internal network capture and analysis just got funded. Get taps and monitoring in ASAP.',
    effect: { kind: 'modifier', value: 5, label: '+5 on your next roll' } },
];

export const SITE_TYPES = {
  hq:         { label: 'Headquarters', glyph: 'HQ' },
  office:     { label: 'Regional Office', glyph: 'OF' },
  datacenter: { label: 'Data Center', glyph: 'DC' },
  cloud:      { label: 'Cloud Region', glyph: 'CL' },
  factory:    { label: 'Factory', glyph: 'FA' },
  soc:        { label: 'Security Ops Center', glyph: 'SOC' },
};

// Fictional company: Novacore Industries. Real-world coordinates for the globe.
export const WORLD = {
  company: 'Novacore Industries',
  nodes: [
    { id: 'chi', name: 'Chicago HQ',        city: 'Chicago',    siteType: 'hq',         lat: 41.88,  lng: -87.63 },
    { id: 'aus', name: 'Austin SOC',        city: 'Austin',     siteType: 'soc',        lat: 30.27,  lng: -97.74 },
    { id: 'va',  name: 'Ashburn DC',        city: 'Ashburn',    siteType: 'datacenter', lat: 39.04,  lng: -77.49 },
    { id: 'or',  name: 'Oregon Cloud',      city: 'Boardman',   siteType: 'cloud',      lat: 45.84,  lng: -119.70 },
    { id: 'sao', name: 'S\u00e3o Paulo Office', city: 'S\u00e3o Paulo', siteType: 'office', lat: -23.55, lng: -46.63 },
    { id: 'lon', name: 'London Office',     city: 'London',     siteType: 'office',     lat: 51.51,  lng: -0.13 },
    { id: 'fra', name: 'Frankfurt DC',      city: 'Frankfurt',  siteType: 'datacenter', lat: 50.11,  lng: 8.68 },
    { id: 'mum', name: 'Mumbai Office',     city: 'Mumbai',     siteType: 'office',     lat: 19.08,  lng: 72.88 },
    { id: 'shz', name: 'Shenzhen Factory',  city: 'Shenzhen',   siteType: 'factory',    lat: 22.54,  lng: 114.06 },
    { id: 'tok', name: 'Tokyo Cloud',       city: 'Tokyo',      siteType: 'cloud',      lat: 35.68,  lng: 139.69 },
    { id: 'sin', name: 'Singapore Office',  city: 'Singapore',  siteType: 'office',     lat: 1.35,   lng: 103.82 },
    { id: 'syd', name: 'Sydney Office',     city: 'Sydney',     siteType: 'office',     lat: -33.87, lng: 151.21 },
  ],
  links: [
    ['chi','va'], ['chi','aus'], ['chi','or'], ['va','lon'], ['va','sao'],
    ['lon','fra'], ['fra','mum'], ['mum','sin'], ['sin','shz'], ['shz','tok'],
    ['sin','syd'], ['aus','va'], ['or','tok'], ['fra','sin'], ['chi','lon'],
  ],
};
